# Causal hypothesis generation

In this method the network generates multiple hypothesis for same observations

CONS: Need to know number of particles in advance

In [1]:
import torch
import numpy as np
import simulation
sim = simulation.Spring(num_particles=4, dynamics='static')

In [2]:
number_of_particles = 4
observation_length = 4
data_frame = sim.sample_trajectory(total_time_steps=10000, sample_freq=50, observation_length=4)
# print(data_frame.to_numpy())
X = np.asarray([data_frame.iloc[i].to_numpy() for i in range(observation_length)])
X = np.reshape(X, (-1, number_of_particles))

In [14]:
particles = 4
features = 2
time_slice = 4

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(particles, 10)
        self.fc2 = torch.nn.Linear(10, particles)
        self.cn1 = torch.nn.Conv2d(time_slice, 1, 1, stride=1)

    def forward(self, x):
        x = torch.from_numpy(x).float()
        x = self.fc1(x)
        x = self.fc2(x)
        # x = self.cn1(x)
        return x

In [15]:
net = Net()
print(X.shape)
print(X)
out = net.forward(X)
print(out)

(8, 4)
[[ 0.19302951 -0.36998324  0.2625579   0.28169686]
 [ 2.17277673  2.98589472  2.72647639  2.07743732]
 [ 0.1671291  -0.36046864  0.27644188  0.28319075]
 [ 2.20620367  2.99723075  2.74219526  2.08999542]
 [ 0.1410968  -0.35056569  0.29019556  0.28455849]
 [ 2.23982835  3.0081403   2.75790814  2.10278824]
 [ 0.11499645 -0.34056069  0.30393453  0.28590693]
 [ 2.27356851  3.0189086   2.77360103  2.11562683]]
tensor([[ 0.0778, -0.4223, -0.4831,  0.1537],
        [-1.3798, -0.6027, -1.5479,  0.2065],
        [ 0.0753, -0.4170, -0.4812,  0.1529],
        [-1.3885, -0.6095, -1.5576,  0.2081],
        [ 0.0728, -0.4117, -0.4793,  0.1521],
        [-1.3971, -0.6164, -1.5674,  0.2098],
        [ 0.0703, -0.4063, -0.4773,  0.1513],
        [-1.4057, -0.6233, -1.5772,  0.2114]], grad_fn=<AddmmBackward>)
